[package]
name = "stalac"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
wgpu = "0.15"
pollster = "0.2"
cgmath = "0.18"
rand = "0.8"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]